// Generates src/styles/icons.css from the Phosphor regular stylesheet, keeping only
// the icons listed in src/ui/icon-names.ts. The font itself is served from the app.

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { ICON_NAMES } from "../src/ui/icon-names.ts";

export const ICONS_CSS = fileURLToPath(new URL("../src/styles/icons.css", import.meta.url));

export function buildIconsCss(phosphorCss: string): string {
  const rules = ICON_NAMES.map((name) => {
    const match = new RegExp(`\\.ph\\.ph-${name}:before\\s*\\{\\s*content:\\s*"([^"]+)";`).exec(
      phosphorCss,
    );
    if (!match?.[1]) throw new Error(`Phosphor regular has no icon named ${name}`);
    return `.ph-${name}::before {\n  content: "${match[1]}";\n}`;
  });
  return [
    "/* Generated by scripts/build-icons.ts from @phosphor-icons/web (regular). Do not edit. */",
    "@font-face {",
    '  font-family: "Phosphor";',
    '  src: url("@phosphor-icons/web/regular/Phosphor.woff2") format("woff2");',
    "  font-weight: normal;",
    "  font-style: normal;",
    "  font-display: block;",
    "}",
    ".ph {",
    '  font-family: "Phosphor" !important;',
    "  speak: never;",
    "  font-style: normal;",
    "  font-weight: normal;",
    "  line-height: 1;",
    "  -webkit-font-smoothing: antialiased;",
    "}",
    ...rules,
    "",
  ].join("\n");
}

export function phosphorRegularCss(): string {
  const require = createRequire(import.meta.url);
  return readFileSync(require.resolve("@phosphor-icons/web/regular"), "utf8");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(ICONS_CSS, buildIconsCss(phosphorRegularCss()), "utf8");
  console.log(`icons: wrote ${ICON_NAMES.length} icons to src/styles/icons.css`);
}
