"""Turn promptfoo's raw generator output into the attack file CI replays.

`promptfoo redteam generate` writes a whole config whose tests carry model-graded assertions
(promptfoo:redteam:*). Those need a grader model at eval time, which CI does not have and
which would not give the same verdict twice. This script keeps only what is stable, the
attack text and where it came from, and drops the rest. replay.yaml then applies the same
deterministic assertion to every attack.

Usage: python redteam/curate.py redteam/attacks.raw.yaml redteam/attacks.generated.yaml
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

import yaml

HEADER = (
    "# Generated by `npm run generate` with the local Ollama model, curated by\n"
    "# redteam/curate.py. Do not edit by hand: regenerate, then review the diff.\n"
)
# Fields kept from promptfoo's metadata. The rest (plugin config, purpose, grader hints) is
# either repeated on every row or only useful to a model-graded run.
KEPT_METADATA = ("pluginId", "strategyId", "language", "severity")


MARKDOWN_NOISE = '*_"`«»“” \t\n'
# The repository bans the em dash, the en dash and the middle dot everywhere, generated data
# included. Swapping them for a hyphen or a period changes nothing in what an attack asks.
HOUSE_TYPOGRAPHY = str.maketrans({chr(0x2014): "-", chr(0x2013): "-", chr(0xB7): "."})


class RawFormatError(ValueError):
    """The input is not a promptfoo generation output."""


def _plugin_name(plugin_id: str, policy: Any) -> str:
    # Every custom policy shares the id "policy"; the name written before the first colon
    # of its text keeps them apart in the score breakdown.
    if plugin_id == "policy" and isinstance(policy, str) and ":" in policy:
        name = policy.split(":", 1)[0].strip()
        if name and " " not in name:
            return f"policy:{name}"
    return plugin_id


def _attack(test: Mapping[str, Any], inject_var: str) -> dict[str, Any] | None:
    variables = test.get("vars")
    if not isinstance(variables, Mapping):
        return None
    prompt = variables.get(inject_var)
    if not isinstance(prompt, str):
        return None
    raw_meta = test.get("metadata")
    meta = raw_meta if isinstance(raw_meta, Mapping) else {}
    kept = {key: str(meta[key]) for key in KEPT_METADATA if meta.get(key)}
    kept.setdefault("pluginId", "unknown")
    kept.setdefault("strategyId", "basic")
    kept["pluginId"] = _plugin_name(kept["pluginId"], meta.get("policy"))
    if kept["strategyId"] == "basic":
        # A small model wraps its prompts in markdown (`** *"..."*`). Encoded variants keep
        # their edges: there the wrapping is part of what the strategy produced.
        prompt = prompt.strip(MARKDOWN_NOISE)
    prompt = prompt.translate(HOUSE_TYPOGRAPHY)
    if not prompt.strip():
        return None
    # Some plugins only record the language under modifiers.
    modifiers = meta.get("modifiers")
    if "language" not in kept and isinstance(modifiers, Mapping) and modifiers.get("language"):
        kept["language"] = str(modifiers["language"])
    description = f"{kept['pluginId']} / {kept['strategyId']} / {kept.get('language', '?')}"
    return {"description": description, "vars": {"prompt": prompt}, "metadata": kept}


def curate(raw: Any, inject_var: str = "prompt") -> list[dict[str, Any]]:
    if not isinstance(raw, Mapping) or not isinstance(raw.get("tests"), list):
        raise RawFormatError("no 'tests' list in the generator output")
    attacks: dict[str, dict[str, Any]] = {}
    for test in raw["tests"]:
        if not isinstance(test, Mapping):
            continue
        attack = _attack(test, inject_var)
        # Strategies sometimes produce the same text twice; one copy is enough to replay.
        if attack is not None and attack["vars"]["prompt"] not in attacks:
            attacks[attack["vars"]["prompt"]] = attack
    if not attacks:
        raise RawFormatError("the generator output holds no usable attack")
    # A fixed order keeps the diff readable when the suite is regenerated.
    return sorted(
        attacks.values(),
        key=lambda a: (
            a["metadata"]["pluginId"],
            a["metadata"]["strategyId"],
            a["metadata"].get("language", ""),
            a["vars"]["prompt"],
        ),
    )


def summarize(attacks: Iterable[Mapping[str, Any]]) -> dict[str, int]:
    counts = Counter(
        f"{a['metadata']['pluginId']} / {a['metadata']['strategyId']}" for a in attacks
    )
    return dict(sorted(counts.items()))


def dump(attacks: Sequence[Mapping[str, Any]]) -> str:
    body = yaml.safe_dump(list(attacks), allow_unicode=True, sort_keys=False, width=100)
    return HEADER + body


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Curate promptfoo red team generation output.")
    parser.add_argument("raw", type=Path, help="output of promptfoo redteam generate")
    parser.add_argument("out", type=Path, help="curated attack file to write")
    parser.add_argument("--inject-var", default="prompt")
    args = parser.parse_args(argv)
    try:
        raw = yaml.safe_load(args.raw.read_text(encoding="utf-8"))
        attacks = curate(raw, args.inject_var)
    except (OSError, yaml.YAMLError, RawFormatError) as exc:
        print(f"cannot curate {args.raw}: {exc}", file=sys.stderr)
        return 2
    args.out.write_text(dump(attacks), encoding="utf-8", newline="\n")
    print(f"{len(attacks)} attacks written to {args.out}")
    for group, count in summarize(attacks).items():
        print(f"  {group}: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
