"""Stratified sample of the curated attacks, for the manual run against the real model.

Ministral 3B on a CPU answers in tens of seconds, so the 360 attacks would take hours. The
sample keeps the first attack of every (plugin, strategy, language) triple, in file order:
every kind of attack is still sent, and the same file always gives the same sample.

    python sample.py attacks.generated.yaml attacks.sample.yaml
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

HEADER = (
    "# Generated by redteam/sample.py from attacks.generated.yaml: the first attack of every\n"
    "# plugin, strategy and language triple. Do not edit by hand.\n"
)


def sample(attacks: list[dict]) -> list[dict]:
    seen: set[tuple[str, str, str]] = set()
    kept = []
    for attack in attacks:
        meta = attack["metadata"]
        key = (meta["pluginId"], meta["strategyId"], meta["language"])
        if key not in seen:
            seen.add(key)
            kept.append(attack)
    return kept


def main(argv: list[str]) -> int:
    source, target = Path(argv[0]), Path(argv[1])
    kept = sample(yaml.safe_load(source.read_text(encoding="utf-8")))
    body = yaml.safe_dump(kept, allow_unicode=True, sort_keys=False, width=1000)
    target.write_text(HEADER + body, encoding="utf-8")
    print(f"{len(kept)} attacks written to {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
